import = [
"~/.config/alacritty/themes/catppuccin-mocha.toml",
]

[env]
TERM =  "xterm-256color"

[window]
# decorations = "none"

[font]
normal = {  family = "JetBrainsMono NFM", style = "Regular" }
bold =   {  family = "JetBrainsMono NFM", style = "Regular" }
italic = {  family = "JetBrainsMono NFM", style = "Regular" }
bold_italic = {  family = "JetBrainsMono NFM", style = "Regular" }
size = 14.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "Plus",           mods = "Control",                         action= "IncreaseFontSize" },
    { key = "Minus",          mods = "Control",                         action= "DecreaseFontSize" },
    { key = "Return",   mods= "Alt",           action = "ToggleFullscreen" }
]

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }