import = ["{{ alacritty-theme }}"]

[env]
TERM = "xterm-256color"

{{ alacritty-shell }}

[window]
startup_mode = "Maximized"
decorations = "full"
dynamic_padding = true
padding = { x = 8, y = 8 }
opacity = 0.9

[colors]
draw_bold_text_with_bright_colors = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
bold_italic = { family = "JetBrainsMono Nerd Font" }
size = 15.0

[selection]
save_to_clipboard = true

[scrolling]
multiplier = 5

[mouse]
hide_when_typing = true

[keyboard]
bindings = [{ key = "w", mods = "Control", action = "Quit" }]
