[general.files]
alacritty = { target = "~/AppData/Roaming/alacritty", type = "template" }
bat = "~/AppData/Roaming/bat"
nvim = "~/AppData/Local/nvim"

[general.variables]
alacritty-theme = "~/AppData/Roaming/alacritty/themes/rose-pine-moon.toml"
alacritty-shell = """
[shell]
program = "wsl"
args = ["--cd ~"]
"""

[linux.variables]
workspaces = "D:/workspace"
