[code.files]
nvim = "~/AppData/Local/nvim"
alacritty = "~/AppData/Roaming/alacritty"

[code.variables]
workspaces = "D:/workspace"
alacritty-theme_path = "~/AppData/Roaming/alacritty/themes/rose-pine-moon.toml"
