# On Windows, '~' is expanded to 'C:\Users\<USERNAME>\'
[code.files]
nvim = { target = "~/.config/nvim", type = "symbolic" }
bin = { target = "~/bin", type = "template" }
".vimrc" = "~/.vimrc"
tmux = "~/.config/tmux"
lazygit = "~/.config/lazygit"
alacritty = "~/.config/alacritty"

[code.variables]
workspaces = "~/workspace"

[shell.files]
".zshenv" = { target = "~/.zshenv", type = "symbolic" }
zsh = { target = "~/.config/zsh", type = "symbolic" }
bat = { target = "~/.config/bat", type = "symbolic" }
"starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

[windows.files]
"./windows/repeat-rates.reg" = { target = "~/.config/repeat-rate.reg", type = "symbolic" }
"./windows/Microsoft.PowerShell_profile.ps1" = { target = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1", type = "symbolic" }
"./windows/powershell/config.ps1" = { target = "~/.config/powershell/config.ps1", type = "symbolic" }

[i3.files]
i3 = { target = "~/.config/i3", type = "symbolic" }
