# On Windows, '~' is expanded to 'C:\Users\<USERNAME>\'
[settings]
default_target_type = "symbolic"

[general.files]
alacritty = "~/.config/alacritty"
bat = "~/.config/bat"
lazygit = "~/.config/lazygit"
nvim = "~/.config/nvim"
wezterm = "~/.config/wezterm"
".gitconfig" = "~/.gitconfig"
"starship.toml" = "~/.config/starship.toml"

[general.variables]
alacritty-theme_path = "~/.config/alacritty/themes/rose-pine-moon.toml"

[windows]
depends = ["general"]

[windows.files]
"./windows/powershell" = "~/.config/powershell"
"./windows/Microsoft.PowerShell_profile.ps1" = "~/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"

[linux]
depends = ["general"]

[linux.files]
"./linux/bin" = { target = "~/bin", type = "template" }
"./linux/dunst" = "~/.config/dunst"
"./linux/foot" = "~/.config/foot"
"./linux/fuzzel" = "~/.config/fuzzel"
"./linux/hypr" = "~/.config/hypr"
"./linux/i3" = "~/.config/i3"
"./linux/Kvantum" = "~/.config/Kvantum"
"./linux/qt5ct" = "~/.config/qt5ct"
"./linux/qt6ct" = "~/.config/qt6ct"
"./linux/tmux" = "~/.config/tmux"
"./linux/waybar" = "~/.config/waybar"
"./linux/zsh" = "~/.config/zsh"
"./linux/.vimrc" = "~/.vimrc"
"./linux/.zshenv" = "~/.zshenv"

[linux.variables]
workspaces = "~/workspace"
