stores:
  json:
    indent: 2
  json_binary:
    indent: 2
  yaml:
    indent: 2

creation_rules:
  - pgp: >-
      E92DE78B88A2C7A7ACE19458B396606FE1B7B6FA
  # upon creation of a file that matches the pattern *.secret.yaml,
  - path_regex: \.secret\.yaml$
    pgp: "E92DE78B88A2C7A7ACE19458B396606FE1B7B6FA"
